### ISSUE TITLE
Demo .env.example

### ISSUE THREAD

**Issue by thefubon** [sidebase/nuxt-auth-example#15]
### Ask your question

Hello. Please fill in with an example file .env.example

I can't figure out how to fill it out correctly.

**Comment by zoey-kaiser** [comment]
Hello @thefubon!

I added an example env in #17! However it may be more helpful to read the description in the Readme, as it goes into more detail of where you can find the variables you need to configure the app!

https://github.com/sidebase/nuxt-auth-example#environment-variables
