### ISSUE TITLE
Polish & Expand show-case to show off more features

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth-example#5]
### Describe the feature

Some features exist that are not yet part of the demo:
- [ ] `getToken`
- [ ] direct signIn with provider, e.g., via `signIn('github')` or `signIn('credentials', {username: 'a', password: 'b'})`

These should be show-cased as well.

Polishing:
- [x] upgrade to `@sidebase/nuxt-auth@0.0.1-beta.6`
- [x] fix failing tests
- [x] #3 

[1]: bar that flickers when logged in:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/25911230/201527652-6b812b16-e54a-47aa-a55b-4f02288190dc.png">

**Comment by MuhammadKhizar7** [comment]
Can you add a database in that example like prisma?, its un clear how claim or token and user data will be stored

**Comment by MuhammadKhizar7** [comment]
Original next-auth use adopter so how can we use it in it or how can we use it in serverless environment like Cloudflare

**Comment by BracketJohn** [comment]
Hey @MuhammadKhizar7!

It works the same as with nextauthJs - you can configure any adapters, db settings, ... in the NuxtAuthHandler!

**Comment by MuhammadKhizar7** [comment]
@BracketJohn Thanks a lot, you really helped me

**Comment by BracketJohn** [comment]
Sure thing - do you want to contribute to our documentation to show an example of how to use adapters? (:
